spring.application.name=Projekt-arendehantering

spring.datasource.url=jdbc:postgresql://localhost:5432/arende
spring.datasource.username=arende
spring.datasource.password=arende

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect