spring.application.name=Projekt-arendehantering

spring.datasource.url=jdbc:postgresql://localhost:5432/arende
spring.datasource.username=arende
spring.datasource.password=arende

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# GitHub OAuth2 Login(hide credentials in production)
spring.security.oauth2.client.registration.github.client-id=Ov23liH2WD75Mu6yIMRq
spring.security.oauth2.client.registration.github.client-secret=63c07ed3f40021ed9a877c06ca09be0a6ef55883
spring.security.oauth2.client.registration.github.scope=read:user,user:email
logging.level.org.springframework.security=DEBUG