# Local development configuration for S3 (Minio)
spring.cloud.aws.credentials.access-key=minioadmin
spring.cloud.aws.credentials.secret-key=minioadmin
spring.sql.init.data-locations=classpath:data.sql,classpath:data-local.sql
